name: Build Multi-Arch

on:
  workflow_call:
    inputs:
      targets:
        description: 'JSON array of targets to build'
        required: false
        default: '["x86_64-unknown-linux-gnu", "armv7-unknown-linux-gnueabihf", "aarch64-unknown-linux-gnu"]'
        type: string
    outputs:
      version:
        description: 'Software version'
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    strategy:
      matrix:
        target: ${{ fromJson(inputs.targets) }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Get version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          VERSION=$(grep '^version = ' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"

    - name: Install compiler
      id: install_cc
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: latest

    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: 'pandemic-console/web/package-lock.json'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install node dependencies and build web assets
      run: |
        npm install
        npm run build
      working-directory: pandemic-console/web

    - name: Install dependencies
      run: |
        cargo install bindgen-cli
        cargo install cross --git https://github.com/cross-rs/cross

    - name: Build
      env:
        CC: ${{ steps.install_cc.outputs.cc }}
        CXX: ${{ steps.install_cc.outputs.cxx }}
        PKG_CONFIG_ALLOW_CROSS: "1"
        BINDGEN_EXTRA_CLANG_ARGS: "-I/usr/include"
      run: cross build --release --target ${{ matrix.target }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/
        include-hidden-files: false